cmake: Disable Fortran when cross-compiling
UIUC-PPL/charm pull request #3403
Opened 2021-07-01 19:48 UTC by matthiasdiener

2021-07-02 03:55 UTC, rbuch approved these changes

2021-07-02 21:27 UTC, matthiasdiener commented
Needs another review.

2021-07-06 22:28 UTC, evan-charmworks commented
I don't agree with merging this unless it's the last thing before the release.

2021-07-12 15:56 UTC, evan-charmworks requested changes
#3417 fixes the Fortran issues.

2021-07-13 19:58 UTC, closed without merging