CkIO read
UIUC-PPL/charm pull request #3675
Opened 2022-12-02 07:09 UTC by mjacob1002

This PR is for the reading capabilities of the CkIO library built on top of Charm++. The additions of this PR are as follows:

1) Added a ReadSession chare array (alternatively called IO chare array) that read the data of the relevant session into the chare array and serve it to the user.

2) Added the infrastructure to create an actual read session with helpers in the impl::Director class

3) implemented the read(Session session, size_t offset, size_t bytes) that actually serves the user the data they want by serving the data to them via a ReadCompleteMsg*. 

4) Added a read_stripe field that will determine how many chares to be used in the IO chare array. 

Also might have to add a sort of "tagging" system for each read so SDAG can be utilized by the user to order the processing of the reads.

2022-12-02 07:10 UTC, mjacob1002 commented
@ZwFink @rbuch If you guys could take a look I would appreciate it!

2022-12-05 06:09 UTC, rbuch requested changes
- [ ] Remove the binaries that were added in this PR (`lb_test`, `period_selection`, and `ping`). 
- [ ] What is the empty file `src/libs/ck-libs/io/headers` supposed to do? If nothing, it should also be removed.
- [ ] Cleanup extraneous comments and output.
- [ ] Cleanup spacing and style.

2022-12-05 06:09 UTC, rbuch commented on src/libs/ck-libs/io/ckio.C
> +			}
Why not just copy directly into `_buffer`?

2022-12-05 06:09 UTC, rbuch commented on src/libs/ck-libs/io/ckio.C
> +			memcpy(msg -> data, buffer, _data_buffer.size());
This doesn't look right, it's copying from `buffer`, but using `_data_buffer`'s size. Has this been tested with a read that requires data from multiple readers?

2022-12-05 06:09 UTC, rbuch commented on src/libs/ck-libs/io/ckio.C
> +
Take out this and other extraneous newlines in the PR.

2022-12-05 06:09 UTC, rbuch commented on src/libs/ck-libs/io/ckio.h
> +
Extra space should be removed. Also, match the commenting style of the other functions here (`///` instead of `/**`).

2022-12-06 23:51 UTC, NK-Nikunj requested changes

2022-12-06 23:51 UTC, NK-Nikunj commented on src/libs/ck-libs/io/Makefile
> +	# touch headers
Remove this comment if it is not required.

2022-12-06 23:51 UTC, NK-Nikunj commented on src/libs/ck-libs/io/ckio.C
> +				std::cerr<< "There was an error on ReadSession chare " << thisIndex << " when trying to open file " << _file -> name << std::endl;
This should use `CkAbort` instead of `std::cerr`

2022-12-06 23:51 UTC, NK-Nikunj commented on src/libs/ck-libs/io/ckio.C
> +		void shareData(size_t read_chare_offset, std::vector<char> data){
Do not use `std::vector<char>` as an entry method parameter. Change this to `char* data, int size`. You can call `data.data(), data.size()` as parameters when calling the function.

2022-12-06 23:51 UTC, NK-Nikunj commented on tests/charm++/load_balancing/lb_test/Makefile
> +OPTS	= -O3 -verbose
-verbose should be removed

2023-03-28 06:44 UTC, mjacob1002 commented
At this point, zero-copy from the ReadSession chares(I/O chares) to the ReadAssembler's ReadInfo struct has been implemented. ReadAssembler has been changed to be a group that manages reads. Structure is now that ReadAssembler is created when startReadSession is invoked, mapping each Session object to the CProxy_ReadAssembler for that session. Then, when a read for a particular session comes in, it's look up in the manager of that PE, and then the ReadAssembler serves the read request. 

The ReadAssembler keeps an internal map for every read request, assigning a library-only tag to map to a ReadInfo struct that contains meta-information about that particular read, including the ReadCompleteMsg* which stores the actual return buffer. ReadSessions still send data to particular ReadAssembler chare, which will then return buffer to user via ReadCompleteMsg*.

2023-06-21 07:08 UTC, closed without merging